ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=5)

      DOUBLE PRECISION MDL_MH,MDL_MZ,MDL_MT,MDL_MW,MDL_MTA

      COMMON/MASSES/ MDL_MH,MDL_MZ,MDL_MT,MDL_MW,MDL_MTA


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_4, GC_5, GC_37

      COMMON/COUPLINGS/ GC_4, GC_5, GC_37

