users={'helsens':1, 
       'selvaggi':2, 
       'djamin':3, 
       'gouskos':4, 
       'vavolkl':5,
       'areigoto':6,
       'rdecarva':7,
       'asung':8,
       'pmandrik':9,
       'jtanaka':10,
       'perfilov':11,
       'amoreira':12,
       'ganis':13,
       'eperez':14,
       'xzuo': 15,
       'fccsw':16
}
